FROM mongo

EXPOSE 27017

# docker build -t oif-mongo .
# docker run --detach --name=oif-mongo --publish 37017:27017 oif-mongo
# https://studio3t.com/knowledge-base/articles/how-to-install-studio-3t-on-linux/