[GENERAL]
API_PORT = 8000
CLIENT_ID = "oc2-orch2"
LOG_LEVEL = "INFO"

[MONGO]
MONGO_URI = "mongodb://127.0.0.1:27017"
MONGO_DATABASE = "oif-mongo"

[MQTT]
# PROTOCOL = "MQTTv5"
PROTOCOL = "MQTTv311"

TRANSPORT = "tcp"
# TRANSPORT = "websockets"

# BROKER = "3271a3ddd2eb43caa7c4b195c7d6cabd.s2.eu.hivemq.cloud"
BROKER = "test.mosquitto.org"

# PORT = 8883
PORT = 1883

# USERNAME = 'Cav01'
# PASSWORD = 'Tango01Village'
USERNAME = ''
PASSWORD = ''

# SEND_TOPICS = ["oc2/cmd","oc2/cmd/all", "oc2/cmd/ap/hunt"]
SEND_TOPICS = ["oc2/cmd/all"]
RESPONSE_TOPICS = ["oc2/rsp"]

# Other Brokers
# broker = "localhost"
# broker = "mosquitto.olympus.mtn" # Local SB Lab Broker
# broker = "test.mosquitto.org" # External Test Broker